-- MySQL Script generated by MySQL Workbench
-- Tue 11 Aug 2020 11:42:07 AM +04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema coco-projet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `coco-projet` ;

-- -----------------------------------------------------
-- Schema coco-projet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coco-projet` DEFAULT CHARACTER SET latin1 ;
USE `coco-projet` ;

-- -----------------------------------------------------
-- Table `coco-projet`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coco-projet`.`admins` ;

CREATE TABLE IF NOT EXISTS `coco-projet`.`admins` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `adminscol_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;

--
-- Dumping data for table `admins`
--

LOCK TABLES `admins` WRITE;
/*!40000 ALTER TABLE `admins` DISABLE KEYS */;
INSERT INTO `admins` VALUES (1,'Anne-Gaëlle','admin@mail.com',NULL,'$2y$10$MReXTVnzqbJzW3ra/HuxlevcXcMp1JX/9PaQc1tjJXdDqAF6oEAgK',NULL);
/*!40000 ALTER TABLE `admins` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `coco-projet`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coco-projet`.`users` ;

CREATE TABLE IF NOT EXISTS `coco-projet`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `address_plus` VARCHAR(255) NULL DEFAULT NULL,
  `postal_code` CHAR(5) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `country` CHAR(2) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `phone_plus` VARCHAR(10) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

LOCK TABLES `users` WRITE;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` VALUES (1,'agent_jenny','jenny@mail.com',NULL,'$2y$10$MReXTVnzqbJzW3ra/HuxlevcXcMp1JX/9PaQc1tjJXdDqAF6oEAgK','rW1FqY3gPU4tSjgnapX9oqtRNgfe99lVsfZLUdyhtAcg5b85YoP2Vul4oXCk','Jenny','Techer','10, rue de Paris','Résidence Manguier, Apt 5','97400','Saint-Denis','RE','0692010205','0692020202',NULL,'2020-07-21 07:36:03');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `coco-projet`.`veterinaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coco-projet`.`veterinaries` ;

CREATE TABLE IF NOT EXISTS `coco-projet`.`veterinaries` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `address_practice` VARCHAR(255) NOT NULL,
  `address_plus_practice` VARCHAR(255) NULL DEFAULT NULL,
  `postal_code_practice` CHAR(5) NOT NULL,
  `city_practice` VARCHAR(50) NOT NULL,
  `country_practice` CHAR(2) NOT NULL,
  `phone_practice` VARCHAR(10) NOT NULL,
  `phone_plus_practice` VARCHAR(10) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

--
-- Dumping data for table `veterinaries`
--

LOCK TABLES `veterinaries` WRITE;
/*!40000 ALTER TABLE `veterinaries` DISABLE KEYS */;
INSERT INTO `veterinaries` VALUES (1,'vet974','veto@mail.com',NULL,'$2y$10$MReXTVnzqbJzW3ra/HuxlevcXcMp1JX/9PaQc1tjJXdDqAF6oEAgK','','Jean','Dupont','195, Rue Marius et Ary Leblond',NULL,'97400','Saint-Denis','RE','0692010101',NULL,NULL,NULL);
/*!40000 ALTER TABLE `veterinaries` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `coco-projet`.`health_records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coco-projet`.`health_records` ;

CREATE TABLE IF NOT EXISTS `coco-projet`.`health_records` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

--
-- Dumping data for table `health_records`
--

LOCK TABLES `health_records` WRITE;
/*!40000 ALTER TABLE `health_records` DISABLE KEYS */;
INSERT INTO `health_records` VALUES (1);
/*!40000 ALTER TABLE `health_records` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `coco-projet`.`animals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coco-projet`.`animals` ;

CREATE TABLE IF NOT EXISTS `coco-projet`.`animals` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `type` VARCHAR(45) NOT NULL,
  `breed` VARCHAR(255) NULL DEFAULT NULL,
  `users_id` BIGINT(20) UNSIGNED NOT NULL,
  `veterinary_id` BIGINT(20) UNSIGNED NOT NULL,
  `health_records_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`last_name` ASC),
  INDEX `fk_animal_veterinary1_idx` (`veterinary_id` ASC),
  INDEX `fk_animal_users_idx` (`users_id` ASC),
  INDEX `fk_animals_health_records1_idx` (`health_records_id` ASC),
  CONSTRAINT `fk_animal_users_idx`
    FOREIGN KEY (`users_id`)
    REFERENCES `coco-projet`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_veterinary1_idx`
    FOREIGN KEY (`veterinary_id`)
    REFERENCES `coco-projet`.`veterinaries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animals_health_records1`
    FOREIGN KEY (`health_records_id`)
    REFERENCES `coco-projet`.`health_records` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

--
-- Dumping data for table `animals`
--

LOCK TABLES `animals` WRITE;
/*!40000 ALTER TABLE `animals` DISABLE KEYS */;
INSERT INTO `animals` VALUES (1,'Bobby','Techer','2018-09-24','chien','Berger Allemand',1,1,1,NULL,NULL);
/*!40000 ALTER TABLE `animals` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `coco-projet`.`failed_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coco-projet`.`failed_jobs` ;

CREATE TABLE IF NOT EXISTS `coco-projet`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coco-projet`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coco-projet`.`migrations` ;

CREATE TABLE IF NOT EXISTS `coco-projet`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

--
-- Dumping data for table `migrations`
--

LOCK TABLES `migrations` WRITE;
/*!40000 ALTER TABLE `migrations` DISABLE KEYS */;
INSERT INTO `migrations` VALUES (1,'2014_10_12_000000_create_users_table',1),(2,'2019_08_19_000000_create_failed_jobs_table',1),(3,'2020_05_05_000002_create_veterinaries_table',1),(4,'2020_05_05_000003_create_health_records_table',1),(5,'2020_05_05_000004_create_animals_table',1);
/*!40000 ALTER TABLE `migrations` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `coco-projet`.`treatments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coco-projet`.`treatments` ;

CREATE TABLE IF NOT EXISTS `coco-projet`.`treatments` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sante_soin` VARCHAR(5) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `nom_produit` VARCHAR(255) NULL DEFAULT NULL,
  `effectue_par` VARCHAR(255) NULL DEFAULT NULL,
  `remarques` VARCHAR(255) NULL DEFAULT NULL,
  `rappel` VARCHAR(3) NULL DEFAULT 'non',
  `created_at` TIMESTAMP NOT NULL DEFAULT now(),
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `health_records_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_entries_health_records1_idx` (`health_records_id` ASC),
  CONSTRAINT `fk_entries_health_records1`
    FOREIGN KEY (`health_records_id`)
    REFERENCES `coco-projet`.`health_records` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

--
-- Dumping data for table `treatments`
--

-- LOCK TABLES `treatments` WRITE;
-- /*!40000 ALTER TABLE `treatments` DISABLE KEYS */;
-- INSERT INTO `treatments` VALUES (1,'santé','Vermifuge','2020-08-11 04:30:34','','propriétaire',NULL,'non','2020-08-11 04:30:34',NULL,1),(2,'soin','Toilettage','2020-08-11 06:00:17',NULL,'toiletteur',NULL,'non','2020-08-11 06:00:17',NULL,1),(3,'santé','RDV vétérinaire','2020-08-15 15:30:00',NULL,NULL,'non','2020-08-15 15:30:00','2020-08-11 07:23:00',NULL,1);
-- /*!40000 ALTER TABLE `treatments` ENABLE KEYS */;
-- UNLOCK TABLES;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
