-- MySQL Script generated by MySQL Workbench
-- Mon 14 Sep 2020 11:33:40 AM +04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema coco-projet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coco-projet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coco-projet` DEFAULT CHARACTER SET latin1 ;
USE `coco-projet` ;

-- -----------------------------------------------------
-- Table `coco-projet`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coco-projet`.`admins` ;

CREATE TABLE IF NOT EXISTS `coco-projet`.`admins` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `adminscol_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coco-projet`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coco-projet`.`users` ;

CREATE TABLE IF NOT EXISTS `coco-projet`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `address_plus` VARCHAR(255) NULL DEFAULT NULL,
  `postal_code` CHAR(5) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `country` CHAR(2) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `phone_plus` VARCHAR(10) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coco-projet`.`veterinaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coco-projet`.`veterinaries` ;

CREATE TABLE IF NOT EXISTS `coco-projet`.`veterinaries` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `address_practice` VARCHAR(255) NOT NULL,
  `address_plus_practice` VARCHAR(255) NULL DEFAULT NULL,
  `postal_code_practice` CHAR(5) NOT NULL,
  `city_practice` VARCHAR(50) NOT NULL,
  `country_practice` CHAR(2) NOT NULL,
  `phone_practice` VARCHAR(10) NOT NULL,
  `phone_plus_practice` VARCHAR(10) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coco-projet`.`health_records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coco-projet`.`health_records` ;

CREATE TABLE IF NOT EXISTS `coco-projet`.`health_records` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coco-projet`.`animals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coco-projet`.`animals` ;

CREATE TABLE IF NOT EXISTS `coco-projet`.`animals` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `type` VARCHAR(45) NOT NULL,
  `breed` VARCHAR(255) NULL DEFAULT NULL,
  `users_id` BIGINT(20) UNSIGNED NOT NULL,
  `veterinary_id` BIGINT(20) UNSIGNED NOT NULL,
  `health_records_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `health_records_id_UNIQUE` (`health_records_id` ASC),
  INDEX `fk_animal_veterinary1_idx` (`veterinary_id` ASC),
  INDEX `fk_animal_users_idx` (`users_id` ASC),
  INDEX `fk_animals_health_records1_idx` (`health_records_id` ASC),
  CONSTRAINT `fk_animal_users_idx`
    FOREIGN KEY (`users_id`)
    REFERENCES `coco-projet`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_veterinary1_idx`
    FOREIGN KEY (`veterinary_id`)
    REFERENCES `coco-projet`.`veterinaries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animals_health_records1`
    FOREIGN KEY (`health_records_id`)
    REFERENCES `coco-projet`.`health_records` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coco-projet`.`treatments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coco-projet`.`treatments` ;

CREATE TABLE IF NOT EXISTS `coco-projet`.`treatments` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sante_soin` VARCHAR(5) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `nom_produit` VARCHAR(255) NULL DEFAULT NULL,
  `effectue_par` VARCHAR(255) NULL DEFAULT NULL,
  `remarques` VARCHAR(255) NULL DEFAULT NULL,
  `rappel` VARCHAR(3) NULL DEFAULT 'non',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `health_records_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_entries_health_records1_idx` (`health_records_id` ASC),
  CONSTRAINT `fk_entries_health_records1`
    FOREIGN KEY (`health_records_id`)
    REFERENCES `coco-projet`.`health_records` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
